### PR TITLE
Fix AESCE regression with Clang due to inclusion order changes

### LINKED ISSUE #601: Build failure of aesce.c with older Clang
When compiling for aarch64, since the merge of https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/550, the build fails with Clang ≤15.x. It succeeds with GCC or with Clang ≥16.

Steps to reproduce on aarch64: just build with Clang in the default configuration.

Steps to reproduce on Ubuntu 24.04 x86_64:

1. `apt-get install gcc-13-aarch64-linux-gnu clang-15 clang-16`
2. `clang-15 -target aarch64-linux-gnu --sysroot /usr/aarch64-linux-gnu -I include -I core -I drivers/builtin/include -c drivers/builtin/src/aesce.c`

Error transcript:

```
drivers/builtin/src/aesce.c:178:5: warning: call to undeclared function 'vaeseq_u8'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    AESCE_ENCRYPT_ROUND_X2;
    ^
drivers/builtin/src/aesce.c:164:39: note: expanded from macro 'AESCE_ENCRYPT_ROUND_X2'
#define AESCE_ENCRYPT_ROUND_X2        AESCE_ENCRYPT_ROUND; AESCE_ENCRYPT_ROUND
                                      ^
drivers/builtin/src/aesce.c:160:13: note: expanded from macro 'AESCE_ENCRYPT_ROUND'
    block = vaeseq_u8(block, vld1q_u8(keys)); \
            ^
drivers/builtin/src/aesce.c:178:5: error: assigning to 'uint8x16_t' (vector of 16 'uint8_t' values) from incompatible type 'int'
    AESCE_ENCRYPT_ROUND_X2;
    ^~~~~~~~~~~~~~~~~~~~~~
drivers/builtin/src/aesce.c:164:39: note: expanded from macro 'AESCE_ENCRYPT_ROUND_X2'
#define AESCE_ENCRYPT_ROUND_X2        AESCE_ENCRYPT_ROUND; AESCE_ENCRYPT_ROUND
                                      ^~~~~~~~~~~~~~~~~~~
drivers/builtin/src/aesce.c:160:11: note: expanded from macro 'AESCE_ENCRYPT_ROUND'
    block = vaeseq_u8(block, vld1q_u8(keys)); \
          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
…
```
(many more such errors, evidently some header isn't getting included when it should).

This is a regression since the 1.0.0 release.

Workaround: use Clang ≥16.

### PR DESCRIPTION
**Pull request by gilles-peskine-arm**
Fix https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/601, a regression introduced by https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/550 which just got merged.

## PR checklist

- [x] **changelog** not required because: bug introduced after the last release
- [x] **framework PR** not required
- [x] **mbedtls development PR** not required because: crypto only
- [x] **mbedtls 3.6 PR** https://github.com/Mbed-TLS/mbedtls/pull/10538
- **tests**
    - Locally: `clang-15 -target aarch64-linux-gnu --sysroot /usr/aarch64-linux-gnu -I include -I core -I drivers/builtin/include -c drivers/builtin/src/aesce.c` (see the [issue description](https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/601) for more details). I tested locally as far back as clang 7. Clang 6 and earlier have a different problem: https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/604
    - On the CI: too much hassle, filed as https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/602
    - Check visually that it doesn't regress https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/548

### CODE REVIEW

**Comment by gilles-peskine-arm** [comment]
I'm adding this issue to the 1.1/4.1 LTS board, not because it particularly has to be done before the LTS, but because if we don't merge this, we'll have a regression compared to 1.0. So it's a “should be done before the next minor release” thing, not a “should be done before the next LTS release.”

**Review by davidhorstmann-arm — APPROVED** [review]
LGTM, thanks!

**Review by bjwtaylor — APPROVED** [review]
